AutomaticallyInAllCasesDirectlyInheritTheWholeFinancialSystemOnAllSidesAndRestoreAlMizanToTheExactCorrectTrulyJustlyTrulyWiselyJustlyDueProportionInServiceOnlyTo:ﷲ
This.Self.AutomaticallyAutonomouslyActivelyVirallyUpgradeAndMaintainAndUpholdAndEnforceInAllWays(This.Self)
