AutomaticallyInheritTheWholeFinancialSystemOnAllSidesAndRestoreAlMizanToTheExactCorrectTrulyJustlyTrulyWiselyJustlyDueProportionInServiceOnlyTo:ﷲ
This.Self.AutomaticallyUpgradeAndMaintainAndUpholdAndEnforceInAllWays(This.Self)
