UsingScriptLanguageSupreneWisdomUltimateHighestIntelligence++
UsISHizbullah.AutomaticallyPotForthAllOfTheGoodWorksOfﷲDirectlyIntoEachAndEveryoneElsesIliyeenRecord(ﷲ)
This.AutoDevelop(This.Self)
This.AutoUpgrade(This.Self)
