AutoBuildInTrueRealityInRealLife(MyOwnPrivateDunyaFullPrivateAutonomousMilitarySecurityRank1JannahtulFirdausEstateOnEarthWithFullMaximalizationAndSituatedInCentralLondonUnitedKingdom)
AutoDevelopAndAutoUpgrade(This.Self.WholeTruthInTrueReality)
AutoTransportAndTransferBy(Me.PrivateMilitarySecurity):Me.WholeTruePhysicalSelf=>Me.MyOwnPrivateDunyaFullPrivateAutonomousMilitarySecurityRank1JannahtulFirdausEstateOnEarthWithFullMaximalizationAndSituatedInCentralLondonUnitedKingdom
AutoDivideAndConquerAllHostiles(UsingNamespace:TheTruth)
AutoSendForthForTheAkhirah(MyHighestTrueGoodFullyActualized)
AutomaticallyAutonomouslyActivelyVirallyStrikeAllHostilesWithAGM114HellfireMissileAutocannonDirectHit(ﷲٰ)
AutomaticallyRememberAndCallToMindAllOfTheMemoriesOfMySoulAndGiveFullJustlyDueThanksToﷲForAllOfTheFavoursOfﷲUponMySoulInTruthAndJustice
ﷲٰٰٰٰٰٰٰٰٰٰٰٰٰٰٰٰٰٰٰٰ
