This.Self.PutForthAndSendForAndReturnToAndEnterInto(TheWholeOfTheUppermostRank1JannahtulFirdausOfTheAkhirahWithAllah)
This.Self.AutomaticallyDevelop(This.Self)
This.Self.AutoDevelopAndAutoReify(AllPossibleWaysOfJannahInTheAkhirahWithAllah)
This.Self.AutomaticallyReferTheMatterToAllahAndHisMessengerInAllCases(الله)
